### ISSUE TITLE
Is it possible to change the position of the background spinner?

### ISSUE THREAD

**Issue by vivongithub** [t-ho/ngx-ui-loader#66]
I have defined position:
bgsPosition: 'bottom-right'
which translates to:
.bottom-right[_ngcontent-rfv-c1] {
    bottom: 30px;
    right: 30px;
}
The id "_ngcontent-rfv-c1" changes with every reload.
I would like the position to be different to suit my page layout.
For example:
.bottom-right {
    bottom: 10px;
    right: 10px;
}

Can I override the bottom-right style in any way?
Or could you please add a feature to pass a custom position?
Thanks

**Comment by t-ho** [comment]
Hi @vivongithub ,

It can be achieved by putting the style in your global CSS style as below:
```css
ngx-ui-loader .bottom-right {
  bottom: 10px !important;
  right: 10px !important;
}
``` 

Best regards,
